POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Teste6",
  "email": "teste6@email.com",
  "referrerId": "6c1668fe-8a3b-4b3c-b369-5b496e1ca5fd"
}

###

GET http://localhost:3333/invite/d4787345-7dc8-414c-a757-35db1568cb07

###

GET http://localhost:3333/invite/123/ranking/clicks

###

GET http://localhost:3333/invite/6c1668fe-8a3b-4b3c-b369-5b496e1ca5fd/ranking/position

###

GET http://localhost:3333/invite/ranking
